task/display/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'display'

urlpatterns = [
    path('', views.user_views, name='users'),
    path('add_user/', views.add_user_views, name='add_user'),
    path('user_edit/<int:user_id>/', views.user_edit_views, name='user_edit'),
    path('user_delete/<int:user_id>/', views.user_delete_views, name='user_delete'),
    path('groups/', views.group_views, name='groups'),
    path('add_group/', views.add_group_views, name='add_group'),
    path('group_edit/<int:group_id>/', views.group_edit_views, name='group_edit'),
    path('group_delete/<int:group_id>/', views.group_delete_views, name='group_delete'),
]

task/task/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('display.urls'))
]

task/display/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=100)
    date_joined = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey('Group', on_delete=models.CASCADE)


class Group(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

task/display/views.py
from django.shortcuts import redirect, render
from .models import User, Group


def user_views(request):
    users = User.objects.all()
    return render(request, "display/users.html", {'users': users})


def add_user_views(request):
    groups = Group.objects.all()
    context = {
        'groups': groups
    }

    group = Group.objects.first()

    if group is None:
        context['errors'] = 'First you have to create a group'
        return render(request, 'display/add_user.html', context)

    if request.method == 'POST':

        username = request.POST['username']
        group = request.POST['group']
        try:
            user = User.objects.get(username=username)
            context['errors'] = 'A user with this name already exists'
        except User.DoesNotExist:
            user = User.objects.create(username=username, group=Group.objects.get(id=group))
            user.save()

            return redirect('display:users')
    return render(request, 'display/add_user.html', context)


def user_edit_views(request, user_id):
    user = User.objects.get(pk=user_id)
    groups = Group.objects.all()

    context = {
        'user': user,
        'groups': groups
    }

    if request.method == 'POST':
        username = request.POST['username']
        group = request.POST['group']

        user.username = username
        user.group = Group.objects.get(name=group)
        user.save()

        return redirect('display:users')

    return render(request, 'display/user_edit.html', context)


def user_delete_views(request, user_id):
    user = User.objects.get(pk=user_id)
    user.delete()

    return redirect('display:users')


def group_views(request):
    groups_data = Group.objects.all()
    context = {
        'groups': []
    }
    for group in groups_data:
        group_data = {
            'id': group.pk,
            'name': group.name,
            'description': group.description,
        }

        context['groups'].append(group_data)
    return render(request, 'display/groups.html', context)


def add_group_views(request):
    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']

        if Group.objects.filter(name=name).exists():
            context = {
                'errors': 'A group with this name already exists.'
            }
            return render(request, 'display/add_group.html', context)

        group = Group.objects.create(name=name, description=description)
        group.save()

        return redirect('display:groups')

    return render(request, 'display/add_group.html')


def group_edit_views(request, group_id):
    group = Group.objects.get(pk=group_id)

    context = {
        'group': group,
    }

    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']

        group.name = name
        group.description = description
        group.save()

        return redirect('display:groups')

    return render(request, 'display/group_edit.html', context)


def group_delete_views(request, group_id):
    group = Group.objects.get(pk=group_id)

    if not User.objects.filter(group=group).exists():
        group.delete()
        return redirect('display:groups')
    else:
        return redirect('display:groups')

task/display/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% csrf_token %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block header %}
    {% endblock %}
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <title>Document</title>
</head>
<body class="body-base-page">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'display:users' %}">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'display:groups' %}">Groups</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
</body>
</html>

task/display/templates/display/add_group.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Add Groups</h2>
    <form method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea class="form-control" id="description" name="description" rows="4"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Add Group</button>
    </form>
</div>
{% endblock %}

task/display/templates/display/add_user.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Add User</h2>
    <form method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>

        <div class="mb-3">
            <label for="group" class="form-label">Group</label>
            <select class="form-select" id="group" name="group" required>
                <option value="" disabled selected>Select a group</option>
                {% for group in groups %}
                    <option value="{{ group.id }}">{{ group.name }}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Add User</button>
    </form>
</div>
{% endblock %}

task/display/templates/display/group_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Edit group</h2>
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body-auth card-body p-5">
                    <form method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ group.name }}" required>
                        </div>

                        <div class="mb-3">
                            <label for="description" class="form-label">Description</label>
                            <textarea class="form-control" id="description" name="description" rows="4">{{ group.description }}</textarea>
                        </div>

                        {% if errors %}
                            <h4>{{ errors }}</h4>
                        {% endif %}

                        <button type="submit" class="btn btn-primary">Edit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task/display/templates/display/groups.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2>Group</h2>

    <div class="mx-auto">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Description</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for group in groups %}
            <tr>
              <td>{{ group.id }}</td>
              <td>{{ group.name }}</td>
              <td>{{ group.description }}</td>
              <td>
                <a href="{% url 'display:group_edit' group.id %}" class="btn btn-primary btn-sm">Edit</a>
                <a href="{% url 'display:group_delete' group.id %}" class="btn btn-danger btn-sm">Delete</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    <a href="{% url 'display:add_group' %}" class="btn btn-success">Add Group</a>
  </div>
{% endblock %}

task/display/templates/display/user_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Edit User</h2>
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body-auth card-body p-5">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" class="form-control" name="username" placeholder="Username" value="{{ user.username }}">
                        </div>
                        <div class="mb-3">
                            <select class="form-select" id="group" name="group" required>
                                <option value="" disabled selected>Select a group</option>
                                {% for group in groups %}
                                    <option value="{{ group.name }}" {% if group.name == user.group.name %}selected{% endif %}>
                                        {{ group.name }}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task/display/templates/display/users.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2>Users</h2>

    <div class="mx-auto">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Created</th>
            <th>Group</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
          <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.date_joined }}</td>
            <td>{{ user.group.name }}</td>
            <td>
              <a href="{% url 'display:user_edit' user.id %}" class="btn btn-primary btn-sm">Edit</a>
              <a href="{% url 'display:user_delete' user.id %}" class="btn btn-danger btn-sm">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <a href="{% url 'display:add_user' %}" class="btn btn-success">Add User</a>
  </div>
{% endblock %}